---
language: node_js
node_js:
  - "10"

sudo: required
dist: trusty

addons:
  chrome: stable

cache:
  yarn: true
  directories:
    - $HOME/.npm
    - $HOME/.cache

env:
  - EMBER_TRY_SCENARIO=default
  - EMBER_TRY_SCENARIO=ember-release

matrix:
  fast_finish: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-release

before_install:
  - sudo chown root /opt/google/chrome/chrome-sandbox
  - sudo chmod 4755 /opt/google/chrome/chrome-sandbox
  - yarn global add ember-cli@3.1.3
  - yarn global add bower
  - google-chrome-stable --headless --disable-gpu --no-sandbox --remote-debugging-port=9222 http://localhost &

install:
  - npm install
  - bower install

script:
  - node_modules/.bin/ember try:one $EMBER_TRY_SCENARIO --skip-cleanup
  - if [ "$EMBER_TRY_SCENARIO" == "ember-default" ]; then bash ./scripts/test-generator.sh; fi

after_script:
  - test $EMBER_TRY_SCENARIO == "default" && test $TRAVIS_BRANCH == "dummy-test" && ember build && firebase deploy --project flexberry-ember-security-test --token "$FIREBASE_TOKEN" -m "Travis Build №$TRAVIS_BUILD_NUMBER."
